<%@ Page Title="" Language="C#" MasterPageFile="~/smsMP.master" AutoEventWireup="true" CodeFile="DeleteDealer.aspx.cs" Inherits="Add_DeleteDealer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <style type="text/css">
        .addtable {
            border-collapse: collapse;
            border: 1px solid #ff0000;
            padding: 10px;
            width: 90%;
        }

        .addtableheader {
            background: #db6c19;
            text-align: left;
            padding: 10px 15px 10px 15px;
            color: #ffffff;
            font-size: 1.5em;
            border: 1px solid #db6c19;
        }

        .tdrow1 {
            background-color: #c18558;
            width: 300px;
            padding: 5px 10px 5px 20px;
            border: 1px solid #db6c19;
            font-weight: bold;
        }

        .tdrow2 {
            border: 1px solid #db6c19;
            padding: 4px 10px 4px 10px;
        }

        .textbox {
            padding: 3px 10px 3px 10px;
            width: 250px;
        }

        .Btn {
            padding: 7px 10px 7px 10px;
            background: #cb3131;
            border: 1px solid #cb3131;
            color: #ffffff;
            font-weight: bold;
            border-radius: 10px;
        }

            .Btn:hover {
                background: #ff0000;
                border: 1px solid #2E9AFE;
                color: #000000;
                font-weight: bold;
                -ms-transform: scale(1.5);
                -webkit-transform: scale(1.2);
                transform: scale(1.2);

            }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div class="container">
        <table class="addtable mx-auto mt-5">
            <tr>
                <th colspan="3" class="addtableheader">Delete Dealer Details : </th>
            </tr>
            <tr>
                <td class="tdrow1">Dearler ID : </td>
                <td class="tdrow2">
                    <asp:TextBox ID="txt_dealer_id" runat="server" CssClass="textbox"></asp:TextBox>&nbsp;&nbsp;&nbsp;( example : Dealer ID should be : DL456 )&nbsp;&nbsp;&nbsp;<asp:Button ID="Btn_get_Dealer_details" runat="server" Text=" Get Details " CssClass="Btn" OnClick="Btn_get_Dealer_details_Click" /></td>
            </tr>
        </table>
    </div>
    <div style="margin: 20px 50px 20px 350px;">
        <asp:Label ID="lbl_delete_message" runat="server"></asp:Label>
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="350px"
            AutoGenerateDeleteButton="True" AutoGenerateRows="False"
            DataKeyNames="dealerid" OnItemDeleting="DetailsView1_ItemDeleting">
            <CommandRowStyle BackColor="#6600FF" Font-Bold="True" Font-Overline="False"
                Font-Size="Larger" Font-Strikeout="False" Font-Underline="False"
                ForeColor="White" />
            <Fields>
                <asp:BoundField DataField="dealerid" HeaderText="Dealer ID" />
                <asp:BoundField DataField="dealername" HeaderText="Dealer Name" />
                <asp:BoundField DataField="dealerhouseno" HeaderText="Dealer House No" />
                <asp:BoundField DataField="dealerstreetname" HeaderText="Dealer Street Name" />
                <asp:BoundField DataField="dealerarea" HeaderText="Dealer area" />
                <asp:BoundField DataField="dealerlandmark" HeaderText="Dealer Landmark " />
                <asp:BoundField DataField="dealercity" HeaderText="Dealer City" />
                <asp:BoundField DataField="dealerstate" HeaderText="Dealer State" />
                <asp:BoundField DataField="dealerpincode" HeaderText="Dealer Pin Code" />
                <asp:BoundField DataField="dealercontactno"
                    HeaderText="Dealer ContactNo" />
                <asp:BoundField DataField="dealerlandlineno" HeaderText="dealerlandlineno" />
                <asp:BoundField DataField="dealership_since" HeaderText="dealership_since" />

            </Fields>
            <RowStyle BackColor="#99CCFF" HorizontalAlign="Center" VerticalAlign="Middle" />
        </asp:DetailsView>
    </div>
</asp:Content>

